// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonMediaLibrary: typeof import('~icons/carbon/media-library')['default']
    ICilSettings: typeof import('~icons/cil/settings')['default']
    IMdiPause: typeof import('~icons/mdi/pause')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    Spinner: typeof import('./src/components/spinner.vue')['default']
  }
}

export {}
