/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonMediaLibrary: typeof import('~icons/carbon/media-library')['default']
    ICilSettings: typeof import('~icons/cil/settings')['default']
    IMdiPause: typeof import('~icons/mdi/pause')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    Spinner: typeof import('./src/components/spinner.vue')['default']
  }
}
